name: bloc_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.4.0
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
